# Generated by Django 5.2.3 on 2025-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('awaiting_response', 'Ожидает отклика'), ('in_progress', 'В работе'), ('on_review', 'На проверке'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='draft', max_length=20, verbose_name='статус'),
        ),
    ]
