# Generated by Django 5.2.3 on 2025-06-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0006_service_allows_modifications_service_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modifications_description',
            field=models.TextField(blank=True, null=True, verbose_name='описание правок'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.service', verbose_name='услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='with_modifications',
            field=models.BooleanField(default=False, verbose_name='с правками'),
        ),
    ]
