# Generated by Django 5.2.3 on 2025-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='платформа'),
        ),
    ]
