# Generated by Django 5.2.3 on 2025-06-27 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'приложение к заказу', 'verbose_name_plural': 'приложения к заказу'},
        ),
        migrations.AddField(
            model_name='order',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='Ссылки на примеры работ, которые нравятся клиенту', null=True, verbose_name='ссылки на примеры'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_orders', to=settings.AUTH_USER_MODEL, verbose_name='целевой креатор'),
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='размер файла в байтах'),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='бюджет'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='uploaded_by',
            field=models.ForeignKey(default=2312, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='загружено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='слаг'),
        ),
    ]
