# Generated by Django 5.2.3 on 2025-06-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderattachment_options_order_references_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modifications_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='with_modifications',
        ),
    ]
