# Generated by Django 5.2.3 on 2025-07-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chat_order'),
        ('orders', '0008_order_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='chats.chat', verbose_name='чат'),
        ),
    ]
