# Generated by Django 5.2.3 on 2025-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_systemmessagetemplate_alter_chat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='order',
        ),
    ]
