# Generated by Django 5.2.3 on 2025-06-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Например: 2-3 дня, 1 неделя и т.д.', max_length=100, null=True, verbose_name='Примерное время выполнения'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.service', verbose_name='Услуга'),
        ),
    ]
