# Generated by Django 5.2.3 on 2025-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
    ]
