# Generated by Django 5.2.3 on 2025-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_clientprofile_location_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='available_for_hire',
            field=models.BooleanField(default=True, verbose_name='available for hire'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='average_response_time',
            field=models.DurationField(blank=True, null=True, verbose_name='average response time'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='creator_covers/', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='online status'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname'),
        ),
    ]
