# Generated by Django 5.2.3 on 2025-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_tag_creatorprofile_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='creators', to='core.tag', verbose_name='Tags'),
        ),
    ]
