# Generated by Django 5.2.3 on 2025-06-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_creatorprofile_available_for_hire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.creatorprofile', verbose_name='Профиль креатора')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
