# Generated by Django 5.2.3 on 2025-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_tag_alter_creatorprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimated_time_unit',
            field=models.CharField(choices=[('hour', 'час'), ('day', 'день'), ('week', 'неделя'), ('month', 'месяц'), ('year', 'год')], default='day', max_length=10, verbose_name='Единица измерения времени'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time_value',
            field=models.PositiveIntegerField(default=1, help_text='Количество единиц времени для выполнения услуги', verbose_name='Количество единиц времени'),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Устаревшее поле, оставлено для совместимости', max_length=100, null=True, verbose_name='Примерное время выполнения (устаревшее)'),
        ),
    ]
