# Generated by Django 5.2.3 on 2025-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_sociallink_name_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allows_modifications',
            field=models.BooleanField(default=True, verbose_name='Разрешены правки'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(default=1000, help_text='Например: 2-3 дня, 1 неделя и т.д.', max_length=100, verbose_name='Примерное время выполнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='modifications_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость заказа с возможностью внесения правок', max_digits=10, null=True, verbose_name='Цена с правками'),
        ),
    ]
