# Generated by Django 5.2.3 on 2025-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_service_estimated_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='average_work_time',
            field=models.CharField(blank=True, choices=[('up_to_24_hours', 'До 24 часов'), ('up_to_3_days', 'До 3 дней'), ('up_to_10_days', 'До 10 дней'), ('up_to_14_days', 'До 14 дней'), ('up_to_30_days', 'До 30 дней'), ('up_to_60_days', 'До 60 дней'), ('more_than_60_days', 'Более 60 дней')], default='up_to_3_days', help_text='Среднее время выполнения работы креатором', max_length=30, null=True, verbose_name='average work time'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('prefer_not_to_say', 'Не указывать')], help_text='Пол пользователя для отображения соответствующего значка', max_length=20, null=True, verbose_name='gender'),
        ),
    ]
