# Generated by Django 5.2.3 on 2025-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_creatorprofile_average_work_time_user_gender'),
    ]

    operations = [
        # Сначала добавляем поле
        migrations.AddField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('vkontakte', 'ВКонтакте'), ('dzen', 'Дзен'), ('twitch', 'Twitch')], default='facebook', help_text='Платформа социальной сети', max_length=50, verbose_name='platform'),
            preserve_default=False,
        ),
        # Затем обновляем URL поле
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Ссылка на профиль', verbose_name='url'),
        ),
        # Теперь создаём уникальное ограничение
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('creator_profile', 'platform')},
        ),
        # И в конце удаляем старое поле name
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
    ]