# Generated by Django 5.2.3 on 2025-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_service_allows_modifications_service_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='service_thumbnails/', verbose_name='Обложка услуги'),
        ),
    ]
