# Generated by Django 5.2.3 on 2025-07-19 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sociallink_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_creators', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.creatorprofile', verbose_name='Креатор')),
            ],
            options={
                'verbose_name': 'Избранный креатор',
                'verbose_name_plural': 'Избранные креаторы',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'creator')},
            },
        ),
    ]
