# Generated by Django 5.2.3 on 2025-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('order', 'Тег заказа'), ('creator', 'Тег креатора')], default='order', help_text='Определяет назначение тега (для заказов или креаторов)', max_length=10, verbose_name='тип тега'),
        ),
    ]
